from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash
from datetime import datetime
from app import db, login_manager


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


class User(UserMixin, db.Model):
    """User model for authentication and preferences."""
    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(80), unique=True, nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    password_hash = db.Column(db.String(256), nullable=False)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)

    preferences = db.relationship('MealPreference', backref='user', lazy=True, uselist=False)
    meal_plans = db.relationship('MealPlan', backref='user', lazy=True)

    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)


class MealPreference(db.Model):
    """User meal preferences for AI generation."""
    __tablename__ = 'meal_preferences'

    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)

    # Dietary preferences
    dietary_restrictions = db.Column(db.Text)  # JSON string: vegetarian, vegan, gluten-free, etc.
    allergies = db.Column(db.Text)  # JSON string of allergens
    favorite_foods = db.Column(db.Text)  # JSON string of favorite foods
    disliked_foods = db.Column(db.Text)  # JSON string of disliked foods

    # Goals
    primary_goal = db.Column(db.String(50))  # pleasure, fitness, macro_awareness, variety
    calorie_target = db.Column(db.Integer)
    protein_target = db.Column(db.Integer)
    carb_target = db.Column(db.Integer)
    fat_target = db.Column(db.Integer)

    # Cuisine preferences
    preferred_cuisines = db.Column(db.Text)  # JSON string of cuisines

    # Meal planning preferences
    meals_per_day = db.Column(db.Integer, default=3)
    cooking_skill = db.Column(db.String(20), default='intermediate')  # beginner, intermediate, advanced
    prep_time_preference = db.Column(db.String(20), default='moderate')  # quick, moderate, elaborate
    budget = db.Column(db.String(20), default='moderate')  # budget, moderate, premium

    updated_at = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)


class MealPlan(db.Model):
    """Weekly meal plan generated by AI."""
    __tablename__ = 'meal_plans'

    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
    week_start = db.Column(db.Date, nullable=False)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)

    # AI generated content stored as JSON
    plan_data = db.Column(db.Text, nullable=False)  # JSON with full meal plan
    shopping_list = db.Column(db.Text)  # JSON with consolidated shopping list

    meals = db.relationship('Meal', backref='meal_plan', lazy=True)


class Meal(db.Model):
    """Individual meal within a plan."""
    __tablename__ = 'meals'

    id = db.Column(db.Integer, primary_key=True)
    meal_plan_id = db.Column(db.Integer, db.ForeignKey('meal_plans.id'), nullable=False)

    day_of_week = db.Column(db.Integer, nullable=False)  # 0=Monday, 6=Sunday
    meal_type = db.Column(db.String(20), nullable=False)  # breakfast, lunch, dinner, snack
    name = db.Column(db.String(200), nullable=False)
    description = db.Column(db.Text)
    ingredients = db.Column(db.Text)  # JSON string
    instructions = db.Column(db.Text)
    prep_time = db.Column(db.Integer)  # minutes
    cook_time = db.Column(db.Integer)  # minutes
    calories = db.Column(db.Integer)
    protein = db.Column(db.Integer)
    carbs = db.Column(db.Integer)
    fat = db.Column(db.Integer)
